tunnel: 11970bcb-9686-4e4f-adf5-23a8df65eed3
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: notebook.brandformance.app
    service: http://localhost:8502
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s
      keepAliveTimeout: 90s
      keepAliveConnections: 10
      httpHostHeader: notebook.brandformance.app
  - hostname: trader.brandformance.app
    service: http://localhost:8501
  - service: http_status:404
